apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: camunda
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  dependsOn:
    - name: external-secrets-operator
    - name: external-secrets-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/camunda
  timeout: 2m
  wait: true
