apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  dependsOn:
    - name: external-secrets-operator  
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/external-secrets-config
  wait: true
  timeout: 5m
